version: "3"
services:
  client:
    build: ./client
    container_name: client
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - server
  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
